[tool.poetry]
name = "goit-web-hw-09"
version = "0.1.0"
description = ""
authors = ["mizhik"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.11.2"
mongoengine = "^0.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
